apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kind-shivam-playgroung-1.product-2
  namespace: argocd
  annotations:
    argocd.argoproj.io/refresh-interval: "360s"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    env: dev
    app: product-2
spec:
  project: product-2
  source:
    repoURL: https://github.com/anandshivam44/platform-engineering-research.git
    targetRevision: main
    path: manifests/product-2/kustomize
  destination:
    server: https://kubernetes.default.svc
    namespace: product-2
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    managedNamespaceMetadata:
      labels:
        owner: argocd
      annotations:
        team: sre
