{{- if .Values.pvc.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "product-1.fullname" . }}-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "product-1.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.pvc.accessMode }}
  {{- if .Values.pvc.storageClassName }}
  storageClassName: {{ .Values.pvc.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.pvc.size }}
{{- end }}
