apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kind-shivam-playgroung-1.nginx
  namespace: argocd
  annotations:
    argocd.argoproj.io/refresh-interval: "360s"
  finalizers:
    - resources-finalizer.argocd.argoproj.io # Do not use this is a Company setup
spec:
  project: nginx
  sources:
    - repoURL: https://github.com/anandshivam44/k8-platform-engineering-research.git
      targetRevision: main
      ref: values
    - repoURL: https://charts.bitnami.com/bitnami
      chart: nginx
      targetRevision: "22.5.3"
      helm:
        valueFiles:
          - $values/clusters/kind-shivam-playgroung-1/argocd-applications/nginx/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    managedNamespaceMetadata:
      labels:
        owner: argocd
      annotations:
        team: sre
