apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: product-2-pvc
  namespace: product-2
  labels:
    app: product-2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
