apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: playground-2.app-of-apps
  namespace: argocd
  annotations:
    argocd.argoproj.io/refresh-interval: "360s"
  finalizers:
    - resources-finalizer.argocd.argoproj.io # Do not use this is a Company setup
spec:
  project: default
  sources:
    - repoURL: https://github.com/anandshivam44/k8-platform-engineering-research.git
      targetRevision: main
      path: clusters/kind-shivam-playground-2/argocd-applications/cluster-resources
      directory:
        exclude: "*-secret.yaml"
    - repoURL: https://github.com/anandshivam44/k8-platform-engineering-research.git
      targetRevision: main
      path: clusters/kind-shivam-playground-2/argocd-applications/nginx
      directory:
        exclude: "*-secret.yaml"
    - repoURL: https://github.com/anandshivam44/k8-platform-engineering-research.git
      targetRevision: main
      path: clusters/kind-shivam-playground-2/argocd-applications/product-1
      directory:
        exclude: "*-secret.yaml"
    - repoURL: https://github.com/anandshivam44/k8-platform-engineering-research.git
      targetRevision: main
      path: clusters/kind-shivam-playground-2/argocd-applications/product-2
      directory:
        exclude: "*-secret.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    managedNamespaceMetadata:
      labels:
        owner: argocd
      annotations:
        team: sre
