repositories:
  - name: argo
    url: https://argoproj.github.io/argo-helm

releases:
  - name: argocd
    namespace: argocd
    createNamespace: true
    chart: argo/argo-cd
    version: "9.4.15" # helm chart version (keep in sync with argocd-application.yaml)
    values:
      - ../clusters/kind-shivam-playgroung-1/argocd-applications/argocd/values.yaml
