{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "product-1.fullname" . }}-pdb
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "product-1.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "product-1.selectorLabels" . | nindent 6 }}
{{- end }}
